### ISSUE TITLE
Missing samples for Golang - EMS

### ISSUE THREAD

**Issue by HoRg4sZ** [TIBCOSoftware/TIBCO-Messaging#12]
The readme states that: 
`For example under golang you can find all golang samples/examples for eFTL, EMS, FTL, Kafka, Mosquitto, and TCM.`
However I cannot find any EMS example at: https://github.com/TIBCOSoftware/TIBCO-Messaging/tree/master/samples/golang

Am I missing something?

**Comment by mcarway-arch** [comment]
EMS does not have a golang API, so it would not be applicable.

**Comment by HoRg4sZ** [comment]
If it does not have a golang API then remove it from the readme, it's misleading this way.

**Comment by mcarway-arch** [comment]
Agreed, we will address this in the next pull request. Thanks

**Comment by HoRg4sZ** [comment]
Thank you too!
